<?php
$code=$_COOKIE["Code"];
$name=$_COOKIE["Name"];
$bakmag=$_COOKIE["bakmag"];
$credits=$_COOKIE["Credits"];
$lang=$_COOKIE["Lang"];
$results=$_COOKIE["Results"];
$leclab=$_COOKIE["Leclab"];
$control=$_COOKIE["Control"];
$content=$_COOKIE["Content"];
$devices=$_COOKIE["Devices"];
$opp=$_COOKIE["Select"];

$name1=$_COOKIE["Name_eng"];
$bakmag1=$_COOKIE["bakmag_eng"];
$lang1=$_COOKIE["Lang_eng"];
$results1=$_COOKIE["Results_eng"];
$leclab1=$_COOKIE["Leclab_eng"];
$control1=$_COOKIE["Control_eng"];
$content1=$_COOKIE["Content_eng"];
$devices1=$_COOKIE["Devices_eng"];
$opp1=$_COOKIE["Select_eng"];
